# -*- mode: yaml -*-
# vim:ts=2:sw=2:ai:si:syntax=yaml
---
minimum_pre_commit_version: 2.18.1

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.2.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-yaml
      - id: pretty-format-json
        args: ["--autofix", "--indent=2", "--no-sort-keys"]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v6.0.2
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.17
    hooks:
      - id: shellcheck
      - id: shfmt
        args: ["-l", "-i", "4", "-ci", "-w"]

  - repo: https://github.com/openstack-dev/bashate.git
    rev: "2.1.0"
    hooks:
      - id: bashate

  - repo: https://github.com/igorshubovych/markdownlint-cli.git
    rev: v0.31.1
    hooks:
      - id: markdownlint

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook.git
    rev: "v8.0.0"
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
